spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: service-discovery
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

