server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-customer
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
        - id: ms-order
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
        - id: ms-order
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        - id: ms-product
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
        - id: ms-payment
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**