server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
  show-sql: false

application:
  config:
    customer-url: http://localhost:8091/api/v1/customer
    product-url: http://localhost:8093/api/v1/product
    payment-url: http://localhost:8094/api/v1/payment