server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
  show-sql: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:br.com.hadryan.ecommerce.order.kafka.OrderConfirmation
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderStatusGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.trusted.packages: br.com.hadryan.ecommerce.order.kafka, br.com.hadryan.ecommerce.payment.kafka
          spring.json.type.mapping: orderStatusRequest:br.com.hadryan.ecommerce.order.kafka.OrderStatusRequest

application:
  config:
    customer-url: http://localhost:8090/api/v1/customer
    product-url: http://localhost:8091/api/v1/product
    payment-url: http://localhost:8093/api/v1/payment