server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    flyway:
      baseline-on-migrate: true
      enabled: true
      baseline-version: 0
      baseline-description: "init"
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
    show-sql: false